language: python

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip install -r requirements.txt

before_script:
  - export FLASK_APP=flaskr
  - export FLASK_ENV=development

script:
  - python -m flask run
  - pytest